import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";

export component AppWindow inherits Window {
    title: "Discord Client";
    min-width: 800px;
    min-height: 600px;

    in property <string> visible-name: "Connecting...";
    in property <image> avatar-image;
    in property <[string]> private-channel-names: ["Connecting..."];
    in property <[image]> private-channel-avatars;

    property <color> primary-color: #5865f2;
    property <color> background-color: #36393f;
    property <color> card-color: #2f3136;
    property <color> text-color: #ffffff;

    background: background-color;

    // Guilds column
    Rectangle {
        width: 80px;
        height: parent.height;
        x: 0;
        y: 0;
        background: card-color;

        Rectangle {
            y: 0;
            x: 10px;
            height: parent.height - 70px;
            width: parent.width - 10px;

            // Guild icons here
        }
    }

    // Private channels column
    Rectangle {
        width: 250px;
        height: parent.height;
        x: 80px;
        y: 0;
        background: card-color;

        Rectangle {
            y: 20px;
            x: 5px;
            height: parent.height - 100px;
            width: parent.width - 10px;
            clip: true;

            ScrollView {
                width: parent.width;
                height: parent.height;

                // Private channel cards
                VerticalBox {
                    spacing: 5px;
                    alignment: start;

                    for private-channel[index] in private-channel-names: Rectangle {
                        background: red;
                        height: 35px;
                        border-radius: 5px;
                        clip: true;

                        Rectangle {
                            width: 30px;
                            height: 30px;
                            x: 10px;
                            y: 2.5px;
                            border-radius: 50px;
                            clip: true;
                            background: #2e2d2d;
                            Image {
                                source: private-channel-avatars[index];
                                width: parent.width;
                                height: parent.height;
                            }
                        }

                        Text {
                            text: private-channel;
                            font-size: 14px;
                            x: 50px;
                            width: parent.width - 40px;
                            overflow: TextOverflow.elide;
                        }
                    }
                }
            }
        }
    }

    // Border between Private channels column and Guilds column
    Rectangle {
        x: 80px;
        width: 2px;
        height: parent.height - 110px;
        y: 20px;
        background: background-color.darker(-0.3);
        border-radius: 10px;
    }
    
    // User profile
    Rectangle {
        width: 310px;
        height: 60px;
        y: parent.height - self.height - 10px;
        x: 10px;
        background: background-color;
        border-radius: 8px;

        Rectangle {
            width: 50px;
            height: 50px;
            x: 10px;
            y: 5px;
            border-radius: 50px;
            clip: true;
            background: #2e2d2d;
            Image {
                source: avatar-image;
                width: parent.width;
                height: parent.height;
            }
        }

        Text {
            text: visible-name;
            color: text-color;
            font-size: 16px;
            vertical-alignment: center;
            horizontal-alignment: center;
        }
    }
}
