import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    min-height: 600px;
    min-width: 800px;

    VerticalLayout {
        spacing: 20px;

        Rectangle {
            background: blue;
            width: 100%;
            height: 100px;

            Text {
                text: "dadwaddawdawdawd";
                font-size: 24px;
            }
        }

        Rectangle {
            background: red;
            width: 100%;
            height: 100px;

            Text {
                text: "dawdfadaw";
                font-size: 24px;
            }
        }

        Rectangle {
            background: green;
            width: 100%;
            height: 100px;

            Text {
                text: "dwafwfawfawf";
                font-size: 24px;
            }
        }
    }
}
